cho500/Controllers/HouseholdProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cho500.Entity;
using cho500.Models;
using cho500.Models.Households;
using AutoMapper;
using PagedList;
using Microsoft.Reporting.WebForms;

namespace cho500.Controllers
{
    public class HouseholdProfilesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: HouseholdProfiles
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.RespondentSortParm = String.IsNullOrEmpty(sortOrder) ? "respondent_desc" : "";
            ViewBag.BarangaySortParm = sortOrder == "barangay" ? "barangay_desc" : "barangay";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var householdProfileWithMembers = db.HouseholdProfiles.Include(h => h.HouseholdMembers).ToList();
            List<HouseholdIndexViewModel> householdProfiles = new List<HouseholdIndexViewModel>();

            if (householdProfileWithMembers.Any())
            {
                householdProfiles = Mapper.Map<List<HouseholdProfile>, List<HouseholdIndexViewModel>>(householdProfileWithMembers);
            }
            if (!string.IsNullOrEmpty(searchString))
            {
                householdProfiles = householdProfiles.Where(p => p.Respondent.ToUpper().Contains(searchString.ToUpper())| p.Barangay.ToUpper().Contains(searchString.ToUpper())).ToList();
            }
            switch (sortOrder)
            {
                case "respondent_desc":
                    householdProfiles = householdProfiles.OrderByDescending(s => s.Respondent).ToList();
                    break;
                case "barangay":
                    householdProfiles = householdProfiles.OrderBy(s => s.Barangay).ToList();
                    break;
                case "barangay_desc":
                    householdProfiles = householdProfiles.OrderByDescending(s => s.Barangay).ToList();
                    break;
                default:
                    householdProfiles = householdProfiles.OrderBy(s => s.Respondent).ToList();
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(householdProfiles.ToPagedList(pageNumber, pageSize));
            //return View(householdProfiles);
        }

        // GET: HouseholdProfiles/Details/5
        public ActionResult Details(int? id, string householdProfileID = "Temp")
        {
            if ((id == null) & (householdProfileID == "Temp"))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseholdProfile householdProfile;
            if (id > 0)
            {
                householdProfile = db.HouseholdProfiles.Find(id);
            }
            else
            {
                householdProfile = db.HouseholdProfiles.First(y => y.HouseholdProfileID == householdProfileID);
            }

            var householdMembers = db.HouseholdMembers.Where(y => y.HouseholdProfileID == householdProfile.HouseholdProfileID).ToList();
            if (householdProfile == null)
            {
                return HttpNotFound();
            }
            foreach (HouseholdMember member in householdMembers)
            {
                householdProfile.HouseholdMembers.Add(member);
            }
            return View(householdProfile);
        }

        // GET: HouseholdProfiles/Create
        public ActionResult Create()
        {
            var NonHouseholdMemberPatients = db.Patient.Where(y => y.HouseholdProfileID == null || y.HouseholdProfileID == "").ToList();
            ViewBag.PersonID = new SelectList(NonHouseholdMemberPatients, "PersonID", "FullName");
            ViewBag.BarangayId = new SelectList(db.Barangays, "BarangayID", "Name");
            return View();
        }

        // POST: HouseholdProfiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,HouseholdProfileID,FourPsCCTBeneficiary,Address,BarangayID,PersonId,Note")] HouseholdProfile householdProfile)
        {
            if (ModelState.IsValid)
            {
                db.HouseholdProfiles.Add(householdProfile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var NonHouseholdMemberPatients = db.Patient.Where(y => y.HouseholdProfileID == null || y.HouseholdProfileID == "").ToList();
            ViewBag.PersonID = new SelectList(NonHouseholdMemberPatients, "PersonID", "FullName", householdProfile.PersonID);
            ViewBag.BarangayId = new SelectList(db.Barangays, "BarangayID", "Name", householdProfile.BarangayID);
            return View(householdProfile);
        }

        // GET: HouseholdProfiles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseholdProfile householdProfile = db.HouseholdProfiles.Find(id);
            if (householdProfile == null)
            {
                return HttpNotFound();
            }
            var NonHouseholdMemberPatients = db.Patient.Where(y => y.HouseholdProfileID == null || y.HouseholdProfileID == "" || y.HouseholdProfileID == householdProfile.HouseholdProfileID);
            ViewBag.PersonID = new SelectList(NonHouseholdMemberPatients, "PersonID", "FullName", householdProfile.PersonID);
            ViewBag.BarangayId = new SelectList(db.Barangays, "BarangayID", "Name", householdProfile.BarangayID);

            return View(householdProfile);
        }

        // POST: HouseholdProfiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,HouseholdProfileID,FourPsCCTBeneficiary,Address,BarangayID,PersonId,Note")] HouseholdProfile householdProfile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(householdProfile).State = EntityState.Modified;
                //Person person = db.Patient.Find(householdProfile.PersonID);
                //person.
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var NonHouseholdMemberPatients = db.Patient.Where(y => y.HouseholdProfileID == null || y.HouseholdProfileID == "" || y.HouseholdProfileID == householdProfile.HouseholdProfileID);
            ViewBag.PersonID = new SelectList(NonHouseholdMemberPatients, "PersonID", "FullName", householdProfile.PersonID);
            ViewBag.BarangayId = new SelectList(db.Barangays, "BarangayID", "Name", householdProfile.BarangayID);
            return View(householdProfile);
        }

        // GET: HouseholdProfiles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseholdProfile householdProfile = db.HouseholdProfiles.Find(id);
            if (householdProfile == null)
            {
                return HttpNotFound();
            }
            return View(householdProfile);
        }

        // POST: HouseholdProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HouseholdProfile householdProfile = db.HouseholdProfiles.Find(id);
            var householdMembers = db.Patient.Where(y => y.HouseholdProfileID == householdProfile.HouseholdProfileID).ToList();
            foreach (Person patient in householdMembers)
            {
                patient.HouseholdProfileID = null;
                db.Entry(patient).State = EntityState.Modified;
            }
            db.HouseholdProfiles.Remove(householdProfile);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public FileResult ExportTo(string ReportType)
        {
            LocalReport localReport = new LocalReport();
            localReport.ReportPath = Server.MapPath("~/Reports/HouseholdProfile.rdlc");

            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "DataSet1";
            reportDataSource.Value = db.HouseholdProfiles.ToList();

            localReport.DataSources.Add(reportDataSource);

            string reportType = ReportType;
            string mimeType;
            string encoding;
            string fileNameExtension = (ReportType == "Excel") ? "xlsx" : (ReportType == "Word") ? "docx" : "pdf";
            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;

            renderedBytes = localReport.Render(reportType, "", out mimeType, out encoding,
                                            out fileNameExtension, out streams, out warnings);
            Response.AddHeader("content-disposition", "attachment; filename=HouseholdProfile." + fileNameExtension);

            return File(renderedBytes, fileNameExtension);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

cho500/Views/HouseholdProfiles/Create.cshtml
@model cho500.Entity.HouseholdProfile

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HouseholdProfile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HouseholdProfileID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HouseholdProfileID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HouseholdProfileID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FourPsCCTBeneficiary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.FourPsCCTBeneficiary)
                    @Html.ValidationMessageFor(model => model.FourPsCCTBeneficiary, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Barangay.Name, "BarangayId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BarangayId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Barangay.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Respondent.FullName, "PersonId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Respondent.PersonID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

cho500/Views/HouseholdProfiles/Delete.cshtml
@model cho500.Entity.HouseholdProfile

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HouseholdProfile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.Respondent.FullName)*@
            Respondent
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Respondent.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HouseholdProfileID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HouseholdProfileID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FourPsCCTBeneficiary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FourPsCCTBeneficiary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Barangay.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Barangay.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

cho500/Views/HouseholdProfiles/Details.cshtml
@model cho500.Entity.HouseholdProfile

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>HouseholdProfile</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>@Html.DisplayNameFor(model => model.Respondent.FullName)</dt>*@
        <dt>Respondent Name</dt>
        <dd>@Html.DisplayFor(model => model.Respondent.FullName)</dd>
        <dt>@Html.DisplayNameFor(model => model.HouseholdProfileID)</dt>
        <dd>@Html.DisplayFor(model => model.HouseholdProfileID)</dd>
        <dt>@Html.DisplayNameFor(model => model.FourPsCCTBeneficiary)</dt>
        <dd>@Html.DisplayFor(model => model.FourPsCCTBeneficiary)</dd>
        <dt>@Html.DisplayNameFor(model => model.Address)</dt>
        <dd>@Html.DisplayFor(model => model.Address)</dd>
        <dt>@Html.DisplayNameFor(model => model.Barangay.Name)</dt>
        <dd>@Html.DisplayFor(model => model.Barangay.Name)</dd>
        <dt>@Html.DisplayNameFor(model => model.Note)</dt>
        <dd>@Html.DisplayFor(model => model.Note)</dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Add Household Member", "Create", "HouseholdMembers", new { houseHoldId = Model.HouseholdProfileID },null)
</p>

<table class="table">
    <tr>
        <th>Member Name</th>
        <th>Relation</th>
        <th>Birthday</th>
        <th>PhilHealth</th>
        <th></th>
    </tr>
    @foreach (var item in Model.HouseholdMembers)
    {
        <tr>
            @*<td>@Html.DisplayFor(modelItem => item.Member.FullName)</td>*@
            <td>@Html.ActionLink(item.Member.FullName,"Details","Patient",new { id=item.PersonID},null)</td>
            <td>@Html.DisplayFor(modelItem => item.RelationToHead)</td>
            <td>@Html.DisplayFor(modelItem => item.Member.DateOfBirth)</td>
            <td>@Html.DisplayFor(modelItem => item.Member.PhilHealthNo)</td>
            <td>
                @Html.ActionLink("Edit", "Edit", "HouseholdMembers" ,new { id = item.Id },null) |
                @Html.ActionLink("Details", "Details", "HouseholdMembers", new { id = item.Id },null) |
                @Html.ActionLink("Delete", "Delete", "HouseholdMembers", new { id = item.Id },null)
            </td>
        </tr>
    }
</table>

cho500/Views/HouseholdProfiles/Edit.cshtml
@model cho500.Entity.HouseholdProfile

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.Id)
    
    <div class="form-horizontal">
        <h4>HouseholdProfile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.HouseholdProfileID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HouseholdProfileID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HouseholdProfileID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FourPsCCTBeneficiary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.FourPsCCTBeneficiary)
                    @Html.ValidationMessageFor(model => model.FourPsCCTBeneficiary, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Barangay.Name, "BarangayId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BarangayId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Barangay.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Respondent.FullName, "PersonId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Respondent.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

cho500/Views/HouseholdProfiles/Index.cshtml
@*@model IEnumerable<cho500.Models.Households.HouseholdIndexViewModel>*@
@model PagedList.IPagedList<cho500.Models.Households.HouseholdIndexViewModel>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Household Profile";
}

<h4>Household Profile</h4>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index","HouseholdProfiles",FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("searchString",ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
@*Export To
@Html.ActionLink("Excel", "ExportTo", new { ReportType="Excel"}) |
@Html.ActionLink("PDF", "ExportTo", new { ReportType = "PDF" })*@

<div class="pull-right">
    <div class="btn-group">
        <button type="button" class="btn btn-primary">Export To</button>
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
        <ul class="dropdown-menu">
           <li>@Html.ActionLink("Excel","ExportTo", new { ReportType="Excel"})</li>
           <li>@Html.ActionLink("PDF","ExportTo", new { ReportType="PDF"})</li>   
            <li>@Html.ActionLink("Word", "ExportTo", new { ReportType = "Word" })</li>        
        </ul>
    </div>

</div>

<table class="table">
    <tr>
        <th>@Html.ActionLink("Respondent", "Index", new { sortOrder = ViewBag.RespondentSortParm, currentFilter = ViewBag.CurrentFilter })</th>
        @*<th>Respondent Name</th>*@
        <th>House Hold #</th>
        <th>Beneficiary</th>
        <th>Address</th>
        @*<th>Barangay</th>*@
        <th>@Html.ActionLink("Barangay", "Index", new { sortOrder = ViewBag.BarangaySortParm, currentFilter = ViewBag.CurrentFilter })</th>
        <th>Notes</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.ActionLink(item.Respondent, "Details", "Patient", new { id = item.PersonID }, null)</td>
            <td>@Html.ActionLink(item.HouseholdProfileID, "Details", "HouseholdProfiles", new { id = item.Id }, null)</td>
            <td>@Html.DisplayFor(modelItem => item.FourPsCCTBeneficiary)</td>
            <td>@Html.DisplayFor(modelItem => item.Address)</td>
            <td>@Html.DisplayFor(modelItem => item.Barangay)</td>
            <td>@Html.DisplayFor(modelItem => item.Note)</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
    new
    {
        page,
        sortOrder = ViewBag.CurrentSort,
        currentFilter = ViewBag.CurrentFilter
    }))